apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: corecommerce-web-ingress