apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: corecommerce-web-hpa
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 120 