apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: corecommerce-db-secret
spec:
  refreshInterval: 5m
  target:
    template:
      data:
        connectionString: |
          Server={{ .host }},{{ .port }};Database={{ .dbname }};User Id={{ .username }};Password={{ .password }};Ssl Mode=Require;Trust Server Certificate=true;Pooling=true;Min Pool Size=10;Max Pool Size=100;Connection Idle Lifetime=300;Command Timeout=30;Enable Retry On Failure=true;Retry Count=3;