apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/alb-aws
  - ../../components/cert-manager-prod
  - ../../components/waf-enabled
  - ../../components/alb-logging
  - ../../components/monitoring
  - ../../components/pod-priority

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: corecommerce-web
  - path: hpa-patch.yaml
    target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: corecommerce-web-hpa
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: corecommerce-web-ingress
  - path: pdb-patch.yaml
    target:
      group: policy
      version: v1
      kind: PodDisruptionBudget
      name: corecommerce-web-pdb

configMapGenerator:
  - name: app-settings
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Production
      - Logging__LogLevel__Default=Warning
      - Logging__LogLevel__Microsoft=Error
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Warning

images:
  - name: corecommerce-web
    newTag: stable

vars:
  - name: WAF_ACL_ARN
    objref:
      kind: ConfigMap
      name: environment-config
      apiVersion: v1
    fieldref:
      fieldpath: data.waf_acl_arn