apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: corecommerce-redis-secret
  namespace: corecommerce
  labels:
    app: corecommerce-web
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: redis-connection-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        connectionString: "{{ .endpoint }}:{{ .port }},password={{ .auth_token }},ssl=True,abortConnect=False,connectTimeout=5000,syncTimeout=3000"
  data:
    - secretKey: connectionString
      remoteRef:
        key: corecommerce/dev/redis-auth
        property: ""