apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: corecommerce-db-secret
  namespace: corecommerce
  labels:
    app: corecommerce-web
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: db-connection-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        connectionString: |
          Server={{ .host }},{{ .port }};Database={{ .dbname }};User Id={{ .username }};Password={{ .password }};Ssl Mode=Require;Trust Server Certificate=true;Pooling=true;Min Pool Size=5;Max Pool Size=100;
  data:
    - secretKey: connectionString
      remoteRef:
        key: corecommerce/dev/db-master-password
        property: ""