apiVersion: v1
kind: ServiceAccount
metadata:
  name: corecommerce-web-sa
  namespace: corecommerce
  labels:
    app: corecommerce-web
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/corecommerce-web-role