- op: add
  path: /metadata/annotations/alb.ingress.kubernetes.io~1load-balancer-attributes
  value: access_logs.s3.enabled=true,access_logs.s3.bucket=${LOGGING_BUCKET},access_logs.s3.prefix=${LOGGING_PREFIX}